riscv: module: fix compilation error of kvrealloc
Backporting the patch "riscv: module: Optimize PLT/GOT entry counting" to kernel 6.6.77
leads to compilation error. Error below:

arch/riscv/kernel/module-sections.c: In function 'module_frob_arch_sections':
arch/riscv/kernel/module-sections.c:172:35: error: too few arguments to function 'kvrealloc'
  172 |                         scratch = kvrealloc(scratch, scratch_size, GFP_KERNEL);
      |                                   ^~~~~~~~~

Hence, adding the changes to resolve this compilation error.

Link: https://lore.kernel.org/linux-riscv/20250409024519.454828-1-samuel.holland@sifive.com
Signed-off-by: Pritesh Patel <pritesh.patel@einfochips.com>